### PR TITLE
Build with circleCI

### PR DESCRIPTION
**Pull request by zoff99**
add script file to build with circleCI
test binary after build

https://circleci.com/gh/zoff99/clewarecontrol/25#artifacts

unbenannt

### CODE REVIEW

**Comment by zoff99** [comment]
i have added some tests, and saved all the output files for download.
only the python extension does not work. any ideas why?

unbenannt

**Comment by zoff99** [comment]
can you add a test for the perl extension? any help?

**Comment by flok99** [comment]
Thanks!

**Comment by flok99** [comment]
Hi,

make sure that the .so-file can be found by the linker
e.g. adapt /etc/ld.so.conf of use a preload-path

On Sat, Apr 30, 2016 at 8:32 AM, Zoff <notifications@github.com> wrote:

> i have added some tests, and saved all the output files for download.
> only the python extension does not work. any ideas why?
>
> [image: unbenannt]
> <https://cloud.githubusercontent.com/assets/6833516/14934868/e0c78626-0ebe-11e6-8a20-41487f52b215.PNG>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/clewarecontrol/pull/6#issuecomment-215946694>
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by flok99** [comment]
What do you mean? The included example.pl? Or?

On Sat, Apr 30, 2016 at 8:34 AM, Zoff <notifications@github.com> wrote:

> can you add a test for the perl extension? any help?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/clewarecontrol/pull/6#issuecomment-215946749>
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by zoff99** [comment]
now you should setup a circleCI account. it's free.
and all future PRs will be automatically built and tested before your merge them!
fully integrated with github

**Comment by flok99** [comment]
It doesn't say on the frontpage that it is free?

On Sat, May 7, 2016 at 8:47 AM, Zoff <notifications@github.com> wrote:

> circleCI





-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by zoff99** [comment]
its free for opensource projects. and it uses github login

**Comment by flok99** [comment]
ok done

On Tue, May 10, 2016 at 2:49 PM, Zoff <notifications@github.com> wrote:

> its free for opensource projects. and it uses github login
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/clewarecontrol/pull/6#issuecomment-218181325>
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Pull request merged**
